name: "Create GitHub issue for Leetcode daily problem"
description: "Lookup today's Leetcode daily problem and create a GitHub issue for it"
author: "Jeremy Pruitt"
branding:
  icon: inbox
  color: gray-dark
runs:
  using: "docker"
  image: "Dockerfile"
inputs:
  github_token:
    description: >
      GitHub token for GitHub API requests.
      When `repository` is modified, set to a personal access token with access to `repository`.
    required: true
    default: ${{ github.token }}
  github_repository:
    description: >
      The commit's repository name with owner.
      For example, `jeremypruitt/example-repo`.
    required: true
    default: ${{ github.repository }}
