name: "Create GitHub Issue for Leetcode Daily"
description: "Lookup today's Leetcode daily problem and create a GitHub issue for it"
author: "Jeremy Pruitt"
runs:
  using: "docker"
  image: "Dockerfile"
inputs:
  github_token:
    description: >
      GitHub token for GitHub API requests.
      When `repository` is modified, set to a personal access token with access to `repository`.
    required: true
    default: ${{ github.token }}
